name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install ppretty
        pip install colorama
        pip install unidecode
        pip install sdnotify
        pip install paho-mqtt
        #pip install RPi
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '09_software/*.py')
